config/routes.rb
Rails.application.routes.draw do
  resources :homes, shallow: true do
    resources :rooms, shallow: true do
      resources :items
    end
  end

  root 'homes#index'
  devise_for :users

end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :rooms
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :home
  has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    # homes_as_json = Home.all.to_a.map! { |home| home.to_json }
    respond_to do |format|
      format.html
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])
    @rooms = @home.rooms
    respond_to do |format|
      format.html
      format.json { render json: { home: @home, rooms: @rooms } }
    end
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :street_address, :city, :state, :zip_code)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
    @room = Room.find(params[:room_id])
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.room_id = params[:room_id]

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.room, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @room = @item.room
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @room, notice: "#{@item.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @items = @room.items
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @home = Home.find(params[:home_id])
    @room.home = @home
    respond_to do |format|
      if @room.save
        format.html { redirect_to @home, notice: "The room #{@room.name} was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to home_path(@home), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :home_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label 'Street Address' %><br>
    <%= f.text_field :street_address %><br>
    <%= f.label 'City' %><br>
    <%= f.text_field :city %><br>
    <%= f.label 'State' %><br>
    <%= f.text_field :state %><br>
    <%= f.label 'Zip code' %><br>
    <%= f.text_field :zip_code %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Holiday Home Tour</h1>
  <section ng-controller='homesController as homes'>
    <h2>Homes</h2>
      <div id='homes' ng-repeat="home in homes.homes">
        <home-description></home-description>
      </div>
    <%= link_to 'New Home', new_home_path %>

  </section>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @home.name %></h2>
<%= @home.street_address %><br>
<%= @home.city %><br>
<%= @home.state %><br>
<%= @home.zip_code %><br>


<h3>Rooms</h3>
<ol>
<% @rooms.each do |room| %>
  <li> <%= link_to room.name, room_path(room) %> - <%= link_to 'Edit', '#' %> | <%= link_to 'Delete', room_path(room), method: :delete, data: { confirm: "Sure you want to delete this room?" } %></li>
<% end %>
</ol>

<%= link_to 'Add Room', new_home_room_path(@home) %><br>

<%= link_to 'Edit Home', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/items/_form.html.erb
<%= form_for [@room, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label 'Descrption' %><br>
    <%= f.text_field :description %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='hometourApp'>
<head>
  <title>Holiday Home Tour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>

<div id='items-list'>
  <h2>Items</h2>
  <ol>
  <% @items.each do |item| %>
    <li>
      <span class='item-name'><%= item.name %> | <%= link_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Sure you want to delete?' } %></span> 
      <span class='item-description'><%= item.description %></span>
    </li>
  <% end %>
  </ol>
</div>

<%= link_to 'Add Item', new_room_item_path(@room) %>

app/views/welcome/index.html.erb
<h1>Holiday Home Tour</h1>

<%= link_to 'New User', new_user_registration_path %>